driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
    run_list: apt::default
  - name: debian-8
    run_list: apt::default
  - name: fedora-26
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[squid::default]
    excludes:
      - fedora-26
      - centos-7
      - centos-6
    attributes:
      squid:
        cache_size: 10
        cache_mem: 10
  - name: selinux
    run_list:
      - recipe[test::enforce_selinux]
      - recipe[squid::default]
    verifier:
      inspec_tests:
        - path: ./test/integration/default/
    includes:
      - fedora-26
      - centos-7
      - centos-6
    attributes:
      squid:
        cache_size: 10
        cache_mem: 10
